[features]
seeds = false
[programs.localnet]
solana_gif_portal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/shrinishant/.config/solana/id.json"

[scripts]
test = "node tests/solana-gif-portal.js"
